<%@ Page Title="" Language="VB" MasterPageFile="~/Site.master" AutoEventWireup="false" CodeFile="ManageRoles.aspx.vb" Inherits="Account_ManageRoles" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            width: 269px;
        }
        .style3
        {
            width: 67px;
        }
        .style4
        {
            width: 98px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:Panel runat="server" ID="PnlMsg" >   <asp:ValidationSummary ID="ValidationSummary1" ValidationGroup="Group1" runat="server" HeaderText="" ShowMessageBox="false" DisplayMode="BulletList" ShowSummary="true"  ForeColor="Red" Font-Size="Medium" /><center><asp:Label ID="lblMsg" runat="server" Text=""  Visible="false"></asp:Label></center></asp:Panel>
    
    <table class="style1">
        <tr>
            <td class="style3">
                <h1>
                    Roles</h1>
            </td>
            <td class="style2">
                &nbsp;</td></tr>
                <tr>
            
        </tr>
        <tr>
            <td class="style3" valign="top">
                Role Name</td>
            <td class="style2" valign="top">
                <asp:TextBox ID="txtRoleName" runat="server" Width="150px"></asp:TextBox>
                  <asp:RequiredFieldValidator Display="Dynamic" ID="RequiredFieldValidator1" runat="server"  ControlToValidate="txtRoleName"
                          ErrorMessage="Required" SetFocusOnError="true" Text="*" ValidationGroup="Group1"></asp:RequiredFieldValidator>
                          <asp:RegularExpressionValidator
                              ID="RegularExpressionValidator1" runat="server" Display="Dynamic" ErrorMessage="Invalid RoleName" Text="*" ControlToValidate="txtRoleName" ValidationExpression="^[a-zA-Z'.\s]{1,40}$" ValidationGroup="Group1"></asp:RegularExpressionValidator>
                      <asp:CustomValidator ID="CustomValidator1" runat="server" 
                          ErrorMessage="Aleary Exist" Text="*"   Display="Dynamic" ControlToValidate="txtRoleName" OnServerValidate="CheckExist" ValidationGroup="Group1"  ></asp:CustomValidator>
            </td>
            </tr><tr><td>&nbsp;</td>
            <td class="style4" valign="top">
                <asp:Button ID="btnSubmit" runat="server" Text="Submit"  ValidationGroup="Group1"  /></td>
            <td>
            </tr>
            <tr><td>&nbsp;</td>
                <asp:GridView ID="RolesGrid" runat="server" CellPadding="4" ForeColor="#333333" 
                    GridLines="None" AutoGenerateColumns="false" AutoGenerateDeleteButton="True"   onrowdeleting="RolesGrid_RowDeleting">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                      <Columns>
                  <asp:TemplateField HeaderText="List of available roles" >
                      <ItemTemplate >                       
                          <asp:Label ID="lblRoleName" runat="server" Text="  <%# Container.DataItem.ToString() %>"></asp:Label>
                      </ItemTemplate>
                  </asp:TemplateField>
              </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

